[package]
name = "asdfw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bincode = "1.3"
dirs = "4.0"

[dev-dependencies]
assert_fs = "1.0"
rstest = "0.12"
